version: '3'

services:
  app_test:
    container_name: referral_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - api_test:/app/src/app/
    depends_on:
      - referral_mysql_test
    networks:
      - referral_test

  referral_mysql_test:
   image: mysql:5.7
   container_name: referral_mysql_test
   ports:
     - "3333:3306"
   environment:
     - MYSQL_DATABASE=${TEST_DB_NAME}
     - MYSQL_USER=${TEST_DB_USER}
     - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
     - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
     - DATABASE_HOST=${TEST_DB_HOST}
   networks:
     - referral_test

volumes:
  api_test:

networks:
  referral_test:
    driver: bridge